apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: workday-eoi-sink
  namespace: confluent
spec:
  class: com.example.connectors.GenericHttpSinkConnector
  taskMax: 1
  connectClusterRef:
    name: standard-connect
  configs:
    topics: standard-eda-bentechdata-workday
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: https://psrc-4xgzx.us-east-2.aws.confluent.cloud
    value.converter.basic.auth.credentials.source: USER_INFO
    value.converter.basic.auth.user.info: "KGQ465ZI4MNYQWFH:cfltOREVlPQ9x/CzEtdGmWWPJ408hfBD/0FCNtdL9sgRQlQn3YAkzgdKp6JTrURw"
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: https://psrc-4xgzx.us-east-2.aws.confluent.cloud
    key.converter.basic.auth.credentials.source: USER_INFO
    key.converter.basic.auth.user.info: "KGQ465ZI4MNYQWFH:cfltOREVlPQ9x/CzEtdGmWWPJ408hfBD/0FCNtdL9sgRQlQn3YAkzgdKp6JTrURw"
    consumer.override.security.protocol: SASL_SSL
    consumer.override.sasl.mechanism: PLAIN
    consumer.override.sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='7YWBKDRL7H75S2OY' password='cflt0/af/wDHoajJJLnmJoBRLY0LDC85JmQMbgs8ChG0MI1x/wztPmSaQ9mgnk0Q';"
    content.type: application/xml
    secrets.base.path: /mnt/secrets
    response.topic: standard-eda-bentechdata-workday-response
    error.topic: standard-eda-bentechdata-workday-error
    dlq.topic: standard-eda-bentechdata-workday-dlq
    max.retries: "3"
    retry.backoff.ms: "1000"
    kafka.bootstrap.servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092
    schema.registry.url: https://psrc-4xgzx.us-east-2.aws.confluent.cloud
