apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: generic-hcm-sink-connector
  namespace: confluent
spec:
  class: com.example.connectors.GenericHttpSinkConnector
  taskMax: 1
  connectClusterRef:
    name: dummy-source-connect
  configs:
    topics: dummy-test-topic