apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: dummy-source-connector
  namespace: confluent
spec:
  class: com.example.connectors.DummySourceConnector
  taskMax: 1
  connectClusterRef:
    name: dummy-source-connect
  configs:
    topic: dummy-test-topic